// Original prose written for these store assets. No real book content appears
// in any screenshot - the reader is showing a fictional passage.
window.__FR_PROSE = [
  "There is a particular kind of forgetting that feels like understanding. You read a page, and every sentence lands, and nothing in you resists it. The argument is clear. The examples are apt. You turn the page with the pleasant sense of having taken something in. And then a week later somebody asks you what the chapter was about, and you find that what you took in was the feeling of clarity, not the thing that produced it.",
  "This is not a failure of attention. You were paying attention. It is a failure of retrieval, and retrieval is a separate skill from comprehension - one that reading, by itself, never exercises. Recognition is cheap. Standing in front of the shelf, you know which books you have read. Sitting at a desk with a blank page, you discover how little of them you can reconstruct.",
  "The experiment that makes this concrete is almost unfair in its simplicity. Two groups study the same passage for the same length of time. The first group rereads it four times. The second reads it once and then tries, three times, to write down what it said. Immediately afterwards, the rereaders feel far better prepared, and they say so. A week later they remember roughly half as much.",
  "Confidence, in other words, tracks fluency rather than durability. The passage you have just reread feels available because it is momentarily available, sitting in a kind of short-term glow. The passage you struggled to recall feels unavailable precisely because recalling it was work - and the work is the part that lasts.",
  "Which suggests an uncomfortable rule for anyone trying to learn something properly: the moments that feel most productive are often the least, and the moments that feel like failure are usually where the learning is happening. Effort is not evidence that a method is inefficient. Sometimes it is the only evidence that a method is doing anything at all.",
  "None of this argues against reading. It argues against reading as the whole of study. Read to encounter the idea; then close the book and make yourself produce it. What comes back, in your own clumsy words, is what you actually have. What does not come back was never yours to begin with, however clear it seemed at the time.",
];
